export default function HeroSection() {
  return (
    <section
      className="
      hero-bg
      bg-pattern
      min-h-screen
      flex
      flex-col
      items-center
      justify-center
      relative
      overflow-hidden
      pt-20
    "
    >
      <div
        className="
        absolute
        inset-0
        overflow-hidden
        pointer-events-none
      "
      >
        <div
          className="
          absolute
          top-20
          left-10
          w-px
          h-60
          bg-gradient-to-b
          from-transparent
          via-ouro/30
          to-transparent
        "
        />

        <div
          className="
          absolute
          top-20
          right-10
          w-px
          h-60
          bg-gradient-to-b
          from-transparent
          via-ouro/30
          to-transparent
        "
        />

        <div
          className="
          absolute
          bottom-40
          left-1/2
          -translate-x-1/2
          w-96
          h-px
          bg-gradient-to-r
          from-transparent
          via-ouro/20
          to-transparent
        "
        />
      </div>

      <div
        className="
        relative
        z-10
        text-center
        px-6
        max-w-4xl
        mx-auto
      "
      >
        <div
          className="
          flex
          items-center
          justify-center
          gap-8
          mb-10
          reveal
        "
        >
          <div
            className="
            flex
            flex-col
            items-center
            gap-2
          "
          >
            <img
              src="logo_Templo_Quimbanda.png"
              alt="Quimbanda"
              className="
              w-24
              h-24
              md:w-32
              md:h-32
              object-cover
              rounded-full
              photo-frame
              animate-float
            "
            />

            <span
              className="
              text-fumaca
              text-xs
              font-cinzelPlain
              tracking-widest
              uppercase
            "
            >
              Quimbanda
            </span>
          </div>

          <div
            className="
            text-ouro/40
            text-3xl
            font-cinzel
          "
          >
            ✦
          </div>

          <div
            className="
            flex
            flex-col
            items-center
            gap-2
          "
          >
            <img
              src="logo_Casa_Jurema_Cruzeiro_Luz.png"
              alt="Jurema"
              className="
              w-24
              h-24
              md:w-32
              md:h-32
              object-cover
              rounded-full
              photo-frame
              animate-float
            "
            />

            <span
              className="
              text-fumaca
              text-xs
              font-cinzelPlain
              tracking-widest
              uppercase
            "
            >
              Jurema
            </span>
          </div>
        </div>

        <p
          className="
          font-cinzelPlain
          text-ouro/70
          text-xs
          md:text-sm
          tracking-[0.4em]
          uppercase
          mb-3
        "
        >
          Sacerdote Espiritual
        </p>

        <h1
          className="
          font-cinzel
          text-4xl
          md:text-6xl
          lg:text-7xl
          text-vela
          glow-gold
          leading-tight
          text-shadow-gold
          mb-2
        "
        >
          Tata Edson
        </h1>

        <h2
          className="
          font-cinzel
          text-2xl
          md:text-3xl
          text-ouro
          tracking-widest
          mb-6
        "
        >
          Tertuliano
        </h2>

        <div
          className="
          gold-divider
          max-w-sm
          mx-auto
          mb-6
        "
        />

        <p
          className="
          font-fell
          italic
          text-pergaminho/85
          text-lg
          md:text-xl
          leading-relaxed
          mb-2
        "
        >
          Juremeiro da Casa de Jurema Cruzeiro de Luz
        </p>

        <p
          className="
          font-fell
          italic
          text-pergaminho/85
          text-lg
          md:text-xl
          leading-relaxed
          mb-8
        "
        >
          Sacerdote do Templo de Quimbanda Nordestina
        </p>

        <div
          className="
          flex
          flex-col
          sm:flex-row
          items-center
          justify-center
          gap-4
        "
        >
          <a
            href="https://wa.me/5587981382538?text=Olá%20Tata%20Edson,%20gostaria%20de%20marcar%20uma%20consulta%20espiritual."
            target="_blank"
            rel="noopener noreferrer"
            className="
            whatsapp-btn
            text-noite
            font-cinzelPlain
            font-bold
            text-sm
            tracking-[0.2em]
            uppercase
            px-8
            py-4
            rounded-sm
            shadow-lg
          "
          >
            ✦ Marcar Consulta ✦
          </a>

          <a
            href="#atendimentos"
            className="
            border
            border-ouro/50
            text-ouro
            font-cinzelPlain
            text-sm
            tracking-widest
            uppercase
            px-8
            py-4
            rounded-sm
            hover:bg-ouro/10
          "
          >
            Ver Atendimentos
          </a>
        </div>
      </div>
    </section>
  );
}